sqs:
  local:
    params:
      region: sqs
      endpoint: http://sqs:9324
      apiVersion: "2012-11-05"
    queueName:
      - cvs-edh-test-results-q
  remote:
    params:
      region: "eu-west-1"
      apiVersion: "2012-11-05"
      bucket: cvs-sqs-queues-${BRANCH}
    queueName:
      - cvs-edh-test-results-${BRANCH}-queue
s3:
  local:
    params:
      endpoint: http://s3:9324
  remote:
    params:
      endpoint: https://s3.${AWS_REGION}.amazonaws.com

targets:
  test-results:
    queueName: cvs-edh-dispatcher-test-results-${BRANCH}-queue
  activities:
    queueName: cvs-edh-dispatcher-activities-${BRANCH}-queue
  technical-records:
    queueName: cvs-edh-dispatcher-technical_records-${BRANCH}-queue
